// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with `Firebase.initializeApp()`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BPP2TbHU1Byy7QY7JH2CREr0ucVwV1A',
    appId: '1:827778185994:web:9ac430f6020bd3f1b698f3',
    messagingSenderId: '827778185994',
    projectId: 'runvix-3e27f',
    authDomain: 'runvix-3e27f.firebaseapp.com',
    storageBucket: 'runvix-3e27f.firebasestorage.app',
    measurementId: 'G-7TCDFLSQH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BPP2TbHU1Byy7QY7JH2CREr0ucVwV1A',
    appId: '1:827778185994:android:d6e068e8210352d1b698f3', // Dự đoán ID
    messagingSenderId: '827778185994',
    projectId: 'runvix-3e27f',
    storageBucket: 'runvix-3e27f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0BPP2TbHU1Byy7QY7JH2CREr0ucVwV1A',
    appId: '1:827778185994:ios:76d47b19280bd3f1b698f3', // Dự đoán ID
    messagingSenderId: '827778185994',
    projectId: 'runvix-3e27f',
    storageBucket: 'runvix-3e27f.firebasestorage.app',
    iosBundleId: 'com.example.runvix',
  );
}
